import {
    PAGINATION_SEARCH_SETTINGS,
    ARCHIVED_SEARCH_SETTINGS,
    KEYWORD_SEARCH_SETTINGS,
  } from '../../../../utils/LocationSearchHelper';
  
  export const NATIVE_SEARCH_SETTINGS = [
    ...PAGINATION_SEARCH_SETTINGS,
    ...ARCHIVED_SEARCH_SETTINGS,
    ...KEYWORD_SEARCH_SETTINGS
  ];
  