describe('A Live Event without user point related is correctly displayed on the timeline ', () => {


  it.skip('Should display json source modal', () => {
    cy.get('.ant-timeline-item')
      .eq(1)
      .find('.mcs-card-inner-action')
      .first()
      .as('view_json_source')
    cy.get('.ant-timeline-item')
      .eq(1)
      .find('.mcs-card-title')
      .first()
      .should('have.text', 'Site: mediarithmics')
    cy.get('@view_json_source')
      .should('have.text', 'View JSON source')
      .click()
    cy.get('.ant-modal-content').should('be.visible')
    cy.get('.ant-modal-confirm-title').should('have.text', 'Activity JSON')
    cy.get('.ant-modal-confirm-btns .ant-btn')
      .should('have.text', 'Close')
      .click()
    cy.get('.ant-modal-content').should('not.be.visible')
  })
})
