import {
  PAGINATION_SEARCH_SETTINGS,
  KEYWORD_SEARCH_SETTINGS,
  DATAMART_SEARCH_SETTINGS,
} from '../../../../utils/LocationSearchHelper';

export const PARTITIONS_SEARCH_SETTINGS = [
  ...PAGINATION_SEARCH_SETTINGS,
  ...KEYWORD_SEARCH_SETTINGS,
  ...DATAMART_SEARCH_SETTINGS,
];
