export const ACTION_AUTHORIZATIONS: { [action: string]: string[] } = {
  CREATE_IDENTITY_PROVIDER: ['COMMUNITY_ADMIN', 'CUSTOMER_ADMIN', 'SUPER_ADMIN'],
  ASSOCIATE_IDENTITY_PROVIDER: ['COMMUNITY_ADMIN', 'CUSTOMER_ADMIN', 'SUPER_ADMIN'],
};
