export const ACTION_BAR_BREADCRUMB_POP = 'ACTION_BAR_BREADCRUMB_POP';
export const ACTION_BAR_BREADCRUMB_PUSH = 'ACTION_BAR_BREADCRUMB_PUSH';
export const ACTION_BAR_BREADCRUMB_SET = 'ACTION_BAR_BREADCRUMB_SET';
export const ACTION_BAR_SET_SECONDARY = 'ACTION_BAR_SET_SECONDARY';

export const AUDIENCE_SEGMENTS_DELETE_REQUEST = 'AUDIENCE_SEGMENTS_DELETE_REQUEST';
export const AUDIENCE_SEGMENTS_DELETE_REQUEST_FAILURE = 'AUDIENCE_SEGMENTS_DELETE_REQUEST_FAILURE';
export const AUDIENCE_SEGMENTS_DELETE_REQUEST_SUCCESS = 'AUDIENCE_SEGMENTS_DELETE_REQUEST_SUCCESS';
export const AUDIENCE_SEGMENTS_FETCH_REQUEST = 'AUDIENCE_SEGMENTS_FETCH_REQUEST';
export const AUDIENCE_SEGMENTS_FETCH_REQUEST_FAILURE = 'AUDIENCE_SEGMENTS_FETCH_REQUEST_FAILURE';
export const AUDIENCE_SEGMENTS_FETCH_REQUEST_SUCCESS = 'AUDIENCE_SEGMENTS_FETCH_REQUEST_SUCCESS';
export const AUDIENCE_SEGMENTS_PERFORMANCE_REPORT_FETCH_REQUEST = 'AUDIENCE_SEGMENTS_PERFORMANCE_REPORT_FETCH_REQUEST';
export const AUDIENCE_SEGMENTS_PERFORMANCE_REPORT_FETCH_REQUEST_FAILURE = 'AUDIENCE_SEGMENTS_PERFORMANCE_REPORT_FETCH_REQUEST_FAILURE';
export const AUDIENCE_SEGMENTS_PERFORMANCE_REPORT_FETCH_REQUEST_SUCCESS = 'AUDIENCE_SEGMENTS_PERFORMANCE_REPORT_FETCH_REQUEST_SUCCESS';
export const AUDIENCE_SEGMENTS_TABLE_RESET = 'AUDIENCE_SEGMENTS_TABLE_RESET';

export const CAMPAIGNS_DISPLAY_DELETE_REQUEST = 'CAMPAIGNS_DISPLAY_DELETE_REQUEST';
export const CAMPAIGNS_DISPLAY_DELETE_REQUEST_FAILURE = 'CAMPAIGNS_DISPLAY_DELETE_REQUEST_FAILURE';
export const CAMPAIGNS_DISPLAY_DELETE_REQUEST_SUCCESS = 'CAMPAIGNS_DISPLAY_DELETE_REQUEST_SUCCESS';
export const CAMPAIGNS_DISPLAY_FETCH_REQUEST = 'CAMPAIGNS_DISPLAY_FETCH_REQUEST';
export const CAMPAIGNS_DISPLAY_FETCH_REQUEST_FAILURE = 'CAMPAIGNS_DISPLAY_FETCH_REQUEST_FAILURE';
export const CAMPAIGNS_DISPLAY_FETCH_REQUEST_SUCCESS = 'CAMPAIGNS_DISPLAY_FETCH_REQUEST_SUCCESS';
export const CAMPAIGNS_DISPLAY_PERFORMANCE_REPORT_FETCH_REQUEST = 'CAMPAIGNS_DISPLAY_PERFORMANCE_REPORT_FETCH_REQUEST';
export const CAMPAIGNS_DISPLAY_PERFORMANCE_REPORT_FETCH_REQUEST_FAILURE = 'CAMPAIGNS_DISPLAY_PERFORMANCE_REPORT_FETCH_REQUEST_FAILURE';
export const CAMPAIGNS_DISPLAY_PERFORMANCE_REPORT_FETCH_REQUEST_SUCCESS = 'CAMPAIGNS_DISPLAY_PERFORMANCE_REPORT_FETCH_REQUEST_SUCCESS';
export const CAMPAIGNS_DISPLAY_TABLE_RESET = 'CAMPAIGNS_DISPLAY_TABLE_RESET';

export const CAMPAIGNS_EMAIL_DELETE_REQUEST = 'CAMPAIGNS_EMAIL_DELETE_REQUEST';
export const CAMPAIGNS_EMAIL_DELETE_REQUEST_FAILURE = 'CAMPAIGNS_EMAIL_DELETE_REQUEST_FAILURE';
export const CAMPAIGNS_EMAIL_DELETE_REQUEST_SUCCESS = 'CAMPAIGNS_EMAIL_DELETE_REQUEST_SUCCESS';
export const CAMPAIGNS_EMAIL_DELIVERY_REPORT_FETCH_REQUEST = 'CAMPAIGNS_EMAIL_DELIVERY_REPORT_FETCH_REQUEST';
export const CAMPAIGNS_EMAIL_DELIVERY_REPORT_FETCH_REQUEST_FAILURE = 'CAMPAIGNS_EMAIL_DELIVERY_REPORT_FETCH_REQUEST_FAILURE';
export const CAMPAIGNS_EMAIL_DELIVERY_REPORT_FETCH_REQUEST_SUCCESS = 'CAMPAIGNS_EMAIL_DELIVERY_REPORT_FETCH_REQUEST_SUCCESS';
export const CAMPAIGNS_EMAIL_FETCH_REQUEST = 'CAMPAIGNS_EMAIL_FETCH_REQUEST';
export const CAMPAIGNS_EMAIL_FETCH_REQUEST_FAILURE = 'CAMPAIGNS_EMAIL_FETCH_REQUEST_FAILURE';
export const CAMPAIGNS_EMAIL_FETCH_REQUEST_SUCCESS = 'CAMPAIGNS_EMAIL_FETCH_REQUEST_SUCCESS';
export const CAMPAIGNS_EMAIL_TABLE_RESET = 'CAMPAIGNS_EMAIL_TABLE_RESET';

export const GOAL_ARCHIVE_REQUEST = 'GOAL_ARCHIVE_REQUEST';
export const GOAL_ARCHIVE_REQUEST_FAILURE = 'GOAL_ARCHIVE_REQUEST_FAILURE';
export const GOAL_ARCHIVE_REQUEST_SUCCESS = 'GOAL_ARCHIVE_REQUEST_SUCCESS';
export const GOAL_UPDATE_REQUEST = 'GOAL_UPDATE_REQUEST';
export const GOAL_UPDATE_REQUEST_FAILURE = 'GOAL_UPDATE_REQUEST_FAILURE';
export const GOAL_UPDATE_REQUEST_SUCCESS = 'GOAL_UPDATE_REQUEST_SUCCESS';
export const GOAL_RESET = 'GOAL_RESET';

export const GOALS_PERFORMANCE_REPORT_FETCH_REQUEST = 'GOALS_PERFORMANCE_REPORT_FETCH_REQUEST';
export const GOALS_PERFORMANCE_REPORT_FETCH_REQUEST_FAILURE = 'GOALS_PERFORMANCE_REPORT_FETCH_REQUEST_FAILURE';
export const GOALS_PERFORMANCE_REPORT_FETCH_REQUEST_SUCCESS = 'GOALS_PERFORMANCE_REPORT_FETCH_REQUEST_SUCCESS';
export const GOALS_FETCH_REQUEST = 'GOALS_FETCH_REQUEST';
export const GOALS_FETCH_REQUEST_FAILURE = 'GOALS_FETCH_REQUEST_FAILURE';
export const GOALS_FETCH_REQUEST_SUCCESS = 'GOALS_FETCH_REQUEST_SUCCESS';
export const GOALS_TABLE_RESET = 'GOALS_TABLE_RESET';

export const HEADER_SWITCH_VISIBILITY = 'HEADER_SWITCH_VISIBILITY';

export const LOGIN_REFRESH_TOKEN_REQUEST = 'LOGIN_REFRESH_TOKEN_REQUEST';
export const LOGIN_REFRESH_TOKEN_REQUEST_FAILURE = 'LOGIN_REFRESH_TOKEN_REQUEST_FAILURE';
export const LOGIN_REFRESH_TOKEN_REQUEST_SUCCESS = 'LOGIN_REFRESH_TOKEN_REQUEST_SUCCESS';
export const LOGIN_RESET = 'LOGIN_RESET';

export const SESSION_GET_ACCESS_TOKEN_REQUEST = 'SESSION_GET_ACCESS_TOKEN_REQUEST';
export const SESSION_GET_ACCESS_TOKEN_REQUEST_FAILURE = 'SESSION_GET_ACCESS_TOKEN_REQUEST_FAILURE';
export const SESSION_GET_ACCESS_TOKEN_REQUEST_SUCCESS = 'SESSION_GET_ACCESS_TOKEN_REQUEST_SUCCESS';
export const SESSION_GET_CONNECTED_USER_REQUEST = 'SESSION_GET_CONNECTED_USER_REQUEST';
export const SESSION_GET_CONNECTED_USER_REQUEST_FAILURE = 'SESSION_GET_CONNECTED_USER_REQUEST_FAILURE';
export const SESSION_GET_CONNECTED_USER_REQUEST_SUCCESS = 'SESSION_GET_CONNECTED_USER_REQUEST_SUCCESS';
export const SESSION_GET_WORKSPACES_REQUEST = 'SESSION_GET_WORKSPACES_REQUEST';
export const SESSION_GET_WORKSPACES_REQUEST_FAILURE = 'SESSION_GET_WORKSPACES_REQUEST_FAILURE';
export const SESSION_GET_WORKSPACES_REQUEST_SUCCESS = 'SESSION_GET_WORKSPACES_REQUEST_SUCCESS';
export const SESSION_INIT_WORKSPACE = 'SESSION_INIT_WORKSPACE';
export const SESSION_IS_REACT_URL = 'SESSION_IS_REACT_URL';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
export const SESSION_SWITCH_WORKSPACE = 'SESSION_SWITCH_WORKSPACE';

export const SIDEBAR_SWITCH_VISIBILITY = 'SIDEBAR_SWITCH_VISIBILITY';

export const TRANSLATIONS_FETCH_REQUEST = 'TRANSLATIONS_FETCH_REQUEST';
export const TRANSLATIONS_FETCH_REQUEST_FAILURE = 'TRANSLATIONS_FETCH_REQUEST_FAILURE';
export const TRANSLATIONS_FETCH_REQUEST_SUCCESS = 'TRANSLATIONS_FETCH_REQUEST_SUCCESS';
