import {
  PAGINATION_SEARCH_SETTINGS,
  ARCHIVED_SEARCH_SETTINGS,
  KEYWORD_SEARCH_SETTINGS,
} from '../../../../utils/LocationSearchHelper';

export const CREATIVE_DISPLAY_SEARCH_SETTINGS = [
  ...PAGINATION_SEARCH_SETTINGS,
  ...ARCHIVED_SEARCH_SETTINGS,
  ...KEYWORD_SEARCH_SETTINGS,
];
