const TYPES = {
  IKeywordListService: Symbol.for('KeywordListService'),
  IKeywordListFormService: Symbol.for('KeywordListFormService'),
  IAudienceSegmentService: Symbol.for('audienceSegmentService'),
  IAudienceFeedFormService: Symbol.for('audienceFeedFormService'),
  IAudienceSegmentFormService: Symbol.for('audienceSegmentFormService'),
  IAudiencePartitionsService: Symbol.for('audiencePartitionsService'),
  IAttributionModelService: Symbol.for('attributionModelService'),
  IOverlapInterval: Symbol.for('overlapInterval'),
  IDisplayCampaignFormService: Symbol.for('displayCampaignFormService'),
  IAudienceTagFeedService: Symbol.for('audienceTagFeedService'),
  IAudienceExternalFeedService: Symbol.for('audienceExternalFeedService'),
  IAudienceSegmentFeedService: Symbol.for('audienceSegmentFeedService'),
  IImportService: Symbol.for('importService'),
  IDatamartService: Symbol.for('datamartService'),
  IDisplayNetworkService: Symbol.for('displayNetworkService'),
  IDealListService: Symbol.for('dealListService'),
  IDealListFormService: Symbol.for('dealListFormService'),
  ICompartmentService: Symbol.for('compartmentService'),
  IScenarioService: Symbol.for('scenarioService'),
  IAutomationFormService: Symbol.for('automationFormService'),
  IQueryService: Symbol.for('queryService'),
  IGoalService: Symbol.for('goalService'),
  IGoalFormService: Symbol.for('goalFormService'),
  IExportService: Symbol.for('exportService'),
  IUserDataService: Symbol.for('userDataService'),
  IUsersService: Symbol.for('usersService'),
  IMonitoringService: Symbol.for('monitoringService'),
  IMlAlgorithmService: Symbol.for('mlAlgorithmService'),
  IMlAlgorithmModelService: Symbol.for('mlAlgorithmModelService'),
  IMlAlgorithmVariableService: Symbol.for('mlAlgorithmVariableService'),
  IMlFunctionService: Symbol.for('mlFunctionService'),
  INavigatorService: Symbol.for('navigatorService'),
  IApiTokenService: Symbol.for('apiTokenService'),
  IChannelService: Symbol.for('channelService'),
  ICommunityService: Symbol.for('communityService'),
  IConsentService: Symbol.for('consentService'),
  IGeonameService: Symbol.for('geonameService'),
  ISettingsService: Symbol.for('settingsService'),
  IDashboardService: Symbol.for('dashboardService'),
  ICatalogService: Symbol.for('catalogService'),
  ILibraryCatalogService: Symbol.for('libraryCatalogService'),
  IServiceOfferPageService: Symbol.for('serviceOfferPageService'),
  IFeedsStatsService: Symbol.for('feedsStatsService'),
  IAssetFileService: Symbol.for('assetFileService'),
  IPluginService: Symbol.for('pluginService'),
  ICreativeService: Symbol.for('creativeService'),
  IDisplayCreativeFormService: Symbol.for('displayCreativeFormService'),
  IAdGroupFormService: Symbol.for('adGroupFormService'),
  IDisplayCampaignService: Symbol.for('displayCampaignService'),
  IEmailRouterService: Symbol.for('emailRouterService'),
  IVisitAnalyzerService: Symbol.for('visitAnalyzerService'),
  IRecommenderService: Symbol.for('recommenderService'),
  IAudienceExternalFeedServiceFactory: Symbol.for(
    'audienceExternalFeedServiceFactory',
  ),
  IAudienceTagFeedServiceFactory: Symbol.for('audienceTagFeedServiceFactory'),
  IAudienceSegmentFeedServiceFactory: Symbol.for(
    'audienceSegmentFeedServiceFactory',
  ),
  IAuthService: Symbol.for('authService'),
  IPersistedStoreService: Symbol.for('persistedStoreService'),
  IMicsTagService: Symbol.for('micsTagService'),
  ILabelService: Symbol.for('labelService'),
  IOrganisationService: Symbol.for('organisationService'),
  IDatamartReplicationService: Symbol.for('datamartReplicationService'),
  IDataFileService: Symbol.for('dataFileService'),
  IBidOptimizerService: Symbol.for('bidOptimizerService'),
  IServiceUsageReportService: Symbol.for('serviceUsageReportService'),
  IRuntimeSchemaService: Symbol.for('runtimeSchemaService'),
  IResourceHistoryService: Symbol.for('resourceHistoryService'),
  IReferenceTableService: Symbol.for('referenceTableService'),
  IDatamartUsersAnalyticsService: Symbol.for('datamartUsersAnalyticsService'),
  IEmailCampaignService: Symbol.for('emailCampaignService'),
  IEmailCampaignFormService: Symbol.for('emailCampaignFormService'),
  IPlacementListService: Symbol.for('placementListService'),
  IPlacementListFormService: Symbol.for('placementListFormService'),
};

export { TYPES };
