const TYPES = {
  IKeywordListService: Symbol.for('KeywordListService'),
  IKeywordListFormService: Symbol.for('KeywordListFormService'),
  IAudienceSegmentService: Symbol.for('audienceSegmentService'),
  IAudienceFeedFormService: Symbol.for('audienceFeedFormService'),
  IAudienceSegmentFormService: Symbol.for('audienceSegmentFormService'),
  IAudiencePartitionsService: Symbol.for('audiencePartitionsService'),
  IOverlapInterval: Symbol.for('overlapInterval'),
  IDisplayCampaignFormService: Symbol.for('displayCampaignFormService'),
  IAudienceTagFeedService: Symbol.for('audienceTagFeedService'),
  IAudienceExternalFeedService: Symbol.for('audienceExternalFeedService'),
  IAudienceSegmentFeedService: Symbol.for('audienceSegmentFeedService'),
  IImportService: Symbol.for('importService'),
  IDisplayNetworkService: Symbol.for('displayNetworkService'),
  IDealListService: Symbol.for('dealListService'),
  IDealListFormService: Symbol.for('dealListFormService'),
  ICompartmentService: Symbol.for('compartmentService'),
  IScenarioService: Symbol.for('scenarioService'),
  IAutomationFormService: Symbol.for('automationFormService'),
  IQueryService: Symbol.for('queryService'),
  IGoalFormService: Symbol.for('goalFormService'),
  IExportService: Symbol.for('exportService'),
  IUserDataService: Symbol.for('userDataService'),
  IUsersService: Symbol.for('usersService'),
  IMonitoringService: Symbol.for('monitoringService'),
  IMlAlgorithmService: Symbol.for('mlAlgorithmService'),
  IMlAlgorithmModelService: Symbol.for('mlAlgorithmModelService'),
  IMlFunctionService: Symbol.for('mlFunctionService'),
  INavigatorService: Symbol.for('navigatorService'),
  IApiTokenService: Symbol.for('apiTokenService'),
  IChannelService: Symbol.for('channelService'),
  ICommunityService: Symbol.for('communityService'),
  IConsentService: Symbol.for('consentService'),
  IGeonameService: Symbol.for('geonameService'),
  ISettingsService: Symbol.for('settingsService'),
  IDashboardService: Symbol.for('dashboardService'),
  IAssetFileService: Symbol.for('assetFileService'),
  IPluginService: Symbol.for('pluginService'),
  IPluginInstanceService: Symbol.for('pluginInstanceService'),
  ICreativeService: Symbol.for('creativeService'),
  IDisplayCreativeFormService: Symbol.for('displayCreativeFormService'),
  IAdGroupFormService: Symbol.for('adGroupFormService'),
  IDisplayCampaignService: Symbol.for('displayCampaignService'),
  IEmailRouterService: Symbol.for('emailRouterService'),
  IVisitAnalyzerService: Symbol.for('visitAnalyzerService'),
  IAudienceExternalFeedServiceFactory: Symbol.for(
    'audienceExternalFeedServiceFactory',
  ),
  IAudienceTagFeedServiceFactory: Symbol.for('audienceTagFeedServiceFactory'),
  IAudienceSegmentFeedServiceFactory: Symbol.for(
    'audienceSegmentFeedServiceFactory',
  ),
};

export { TYPES };
